env:
  browser: true
  jquery: true
  jasmine: true
extends:
  'eslint:recommended'
globals:
  define: false
  pageName: false
  require: false
  requirejs: false
  ugcEnabledCollections: false
  window: false
rules:
  no-console:
    - 0
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
