env:
  browser: true

#extends:
#  'eslint:recommended'

globals:
  define: false
  require: false
  window: false
rules:
  no-console:
    - error
    - 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
