env:
  browser: true
extends:
  'eslint:recommended'
globals:
  define: false
  require: false
  window: false
rules:
  no-console:
    - 0
  indent:
    - error
    - 2
  linebreak-style:
    - 1
    - unix
  quotes:
    - 1
    - single
  semi:
    - 1
    - always
