define([], function(){

  var paramName = 'text';

  function log(msg){
    console.log('Demo Autocomplete: ' + msg);
  }

  var data = [
    "The European Library",
    "LoCloud",
    "AthenaPlus",
    "OpenUp!",
    "Hispana",
    "Digitale Collectie",
    "Swedish Open Cultural Heritage",
    "Arts Council Norway",
    "CARARE",
    "Federacja Bibliotek Cyfrowych",
    "Athena",
    "Deutsche Digitale Bibliothek",
    "Linked Heritage",
    "EUscreen",
    "moteur Collections",
    "Europeana Fashion",
    "CultureGrid",
    "National Library of Finland",
    "EuroPhoto",
    "Archives Portal Europe",
    "HOPE - Heritage of the People's Europe",
    "National Library of Poland",
    "EFG - The European Film Gateway",
    "Europeana Sounds",
    "EAGLE",
    "Museu",
    "EUInsideDA",
    "EuropeanaPhotography",
    "Photoconsortium",
    "Judaica Europeana",
    "Europeana 1914-1918",
    "Kulturpool",
    "Rijksmuseum",
    "DK-National Aggregation Service",
    "ECLAP, e-library for Performing Arts",
    "The Wellcome Library",
    "DM2E",
    "European Commission",
    "ASSETS",
    "Hellenic Aggregator at Veria Public Library",
    "EuropeanaLocal Deutschland",
    "Institut National de l'Audiovisuel",
    "MaNDA - Hungarian National Digital Archive and Film Institute",
    "BHL Europe",
    "Archives Départementales de la Gironde",
    "Slovenian National E-content Aggregator",
    "RNOD - Portugal",
    "Swiss National Library",
    "Partage Plus",
    "LT-Aggregator Service National Library of Lithuania",
    "MUSIT",
    "Europeana Food and Drink",
    "thinkMOTION",
    "Biblioteca Virtual Miguel de Cervantes",
    "Slovenski nacionalni agregator e-vsebin",
    "EuropeanaLocal Sweden",
    "Landesarchiv Baden-Württemberg",
    "Lucian Blaga Central University Library, Cluj-Napoca, Romania",
    "Europeana Inside Sweden",
    "Institut de Cultura de Barcelona (ICUB)",
    "Регионална библиотека ПЕНЧО СЛАВЕЙКОВ - Варна / Public Library - Varna",
    "Across Limits",
    "Erfgoedplus.be",
    "MIMO - Musical Instrument Museums Online",
    "Irish Manuscripts Commission",
    "Federico Zeri Foundation",
    "University of Patras/Library and Information Center",
    "Biblioteca de Catalunya",
    "National Library of Latvia",
    "DISMARC",
    "IALHI",
    "Bibliothèque nationale de France",
    "eSbírky",
    "EUscreen Project",
    "Digitising Contemporary Art",
    "Slovenské národné múzeum",
    "Εθνικό Κέντρο Τεκμηρίωσης (ΕΚΤ) | SearchCulture.gr",
    "KAMRA",
    "Muis -Museums Public Portal",
    "EuropeanaLocal Austria",
    "Cyprus Ministry of Education and Culture",
    "Cité de la musique",
    "IRCAM-Institut de Recherche et Coordination Acoustique/Musique",
    "Museumap.hu",
    "Wikimedia Commons Community",
    "The Natural Europe Project",
    "Bibliothèque municipale de Lyon",
    "Médiathèque Valais - Martigny",
    "Daguerreobase",
    "Pamiatkový úrad SR",
    "Békés Megyei Tudásház es Könyvtár, HU",
    "Centre Excursionista de Catalunya",
    "Centre de Documentació de l'Orfeó Català",
    "Vlaamse Kunstcollectie",
    "EuropeanaLocal Portugal",
    "Museo Galileo - Istituto e Museo di Storia della Scienza",
    "Musées lausannois",
    "Institut Cartogràfic i Geològic de Catalunya",
    "OAPEN Foundation",
    "National and University Library in Zagreb",
    "DIZI",
    "Institut Cartogràfic de Catalunya",
    "EuropeanaLocal Romania",
    "Europeana 1989",
    "Diplomatic Documents of Switzerland, dodis.ch",
    "EuropeanaTravel",
    "The Great War Archive, University of Oxford",
    "3D ICONS",
    "National and University Library of Iceland",
    "Universitat de Barcelona",
    "National Library of Romania",
    "Universitätsbibliothek Heidelberg",
    "DASI - Digital Archive for the Study of pre-Islamic Arabian Inscriptions",
    "Universitat Pompeu Fabra",
    "University College Dublin, UCD Library",
    "Fundação Calouste Gulbenkian - Portugal",
    "Národní muzeum, National Museum, Czech Republic",
    "Universitat de Lleida",
    "Instituto dos Museus e da Conservação",
    "University of Ioannina",
    "Diputació de Barcelona",
    "Ateneu Barcelonès",
    "Slovak national gallery",
    "ICAB",
    "Department of Information Management, Hacettepe University",
    "Europeana Local",
    "Universitat Autònoma de Barcelona",
    "Österreichische Mediathek",
    "Filmoteca de Catalunya",
    "Biblioteca Academiei Române",
    "University College Dublin",
    "University of Fribourg - Universitas Friburgensis",
    "Spletna galerija, Semantika d.o.o.",
    "Universitat Politècnica de Catalunya",
    "Niedersächsische Staats- und Universitätsbibliothek Göttingen",
    "Arxiu Històric de Girona",
    "Mediateca de la Universidad de Oviedo - Encycloasturias",
    "EuropeanaConnect - EOD",
    "Museums.EU",
    "Centre de Documentació i Museu Tèxtil",
    "Library of the \"Lucian Blaga\" University of Sibiu",
    "Thyssen-Bornemisza Museum",
    "Bulgariana",
    "Institut d'Estudis Ilerdencs. Servei d'Arxiu i Llegats",
    "Digiphil",
    "Bibliothèques Virtuelles Humanistes",
    "Centre Excursionista de Catalunya (CEC)",
    "Europeana 280",
    "Europeana Space",
    "National Library of Serbia",
    "Instituto de Historia Contemporânea da Faculdade de Ciências Sociais e Humanas da Universidade Nova Lisboa – Portugal",
    "Kultura.hr - Ministry of Culture of the Republic of Croatia",
    "Universitat de Girona. Biblioteca. Fons Bertrana",
    "Casa Àsia, Museu de la Música",
    "National Library or Romania",
    "Biblioteca de Comerç i Turisme de la Generalitat de Catalunya",
    "Il·lustre Col·legi d'Advocats de Barcelona - ICAB",
    "National Library of Greece",
    "Museo Nacional del Prado",
    "Vernadsky National Library of Ukraine",
    "Associació de Mestres Rosa Sensat",
    "Latvijas Nacionâlâ Bibliotçka",
    "The National Bibliographic Office of Malta",
    "Biblioteca de l'Esport de la Generalitat de Catalunya",
    "Biblioteca Museu Víctor Balaguer",
    "3D-COFORM consortium",
    "Biblioteca Nazionale Centrale di Firenze",
    "ICM Ard-Media",
    "Centre de Lectura de Reus",
    "Institut Cartogràfic i Geològic de Catalunya",
    "Universitat de Girona. Biblioteca",
    "Europeana",
    "National Library of Luxembourg",
    "http://digiphil.hu/",
    "APEnet",
    "Biblioteca de l'Orfeó Català",
    "Digital Archive DIGAR / Digitaalarhiiv DIGAR",
    "Europeana development",
    "National Library of Scotland",
    "National Library of the Netherlands - Koninklijke Bibliotheek",
    "Fundació Bosch i Cardellach ; Gremi de Fabricants de Sabadell",
    "Barcelona : Colegio Oficial de Veterinarios de Barcelona",
    "Barcelona : Direcció General d'Agricultura",
    "Barcelona : Ediciones Leti",
    "Barcelona : Escola Superior d'Agricultura",
    "Centre Excursionista de Catalunya",
    "Europeana Office",
    "Liberalisme"
  ];

  var escapeRegExp = function(str){
    return str.replace(/[\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
  };

  return {
    getData: function(params){

      log('params = ' + JSON.stringify(params, null, 4));
      var res  = [];
      var term = params[paramName];
      var re   = new RegExp('\\b' + escapeRegExp(term), 'i');

      $(data).each(function(i, ob){
        if(ob.match(re)){
          res.push($.extend(true, {}, {"text": ob, "organisation_id": i}));
        }
      });

      return res;
    }
  };
});
